package com.mapper;

import com.pojo.Friends;
import com.pojo.FriendsExample;
import com.pojo.User;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface FriendsMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table friends
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table friends
	 *
	 * @mbg.generated
	 */
	int insert(Friends record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table friends
	 *
	 * @mbg.generated
	 */
	int insertSelective(Friends record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table friends
	 *
	 * @mbg.generated
	 */
	List<Friends> selectByExample(FriendsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table friends
	 *
	 * @mbg.generated
	 */
	Friends selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table friends
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Friends record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table friends
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Friends record);

	// 根据username获取好友列表
	List<User> getFriends(@Param("username") String username);
	
	// 是否存在该好友关系
	int isFriend(Friends record);
}