package com.mapper;

import java.util.List;

import com.pojo.Friends;
import com.pojo.Message;
import com.pojo.MessageExample;

public interface MessageMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table message
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table message
	 *
	 * @mbg.generated
	 */
	int insert(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table message
	 *
	 * @mbg.generated
	 */
	int insertSelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table message
	 *
	 * @mbg.generated
	 */
	List<Message> selectByExampleWithBLOBs(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table message
	 *
	 * @mbg.generated
	 */
	List<Message> selectByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table message
	 *
	 * @mbg.generated
	 */
	Message selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table message
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table message
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table message
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Message record);

	// 根据username获取好友列表
	List<String> getFriends(String username);

	// 根据Friends获取信息
	List<Message> getMessage(Friends friends);
	
	//发送信息
	int sendMessage(Message message);
}