package com.pojo;

public class Friends {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friend
     *
     * @mbg.generated
     */
    private String friend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.id
     *
     * @return the value of friends.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.id
     *
     * @param id the value for friends.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.username
     *
     * @return the value of friends.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.username
     *
     * @param username the value for friends.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friend
     *
     * @return the value of friends.friend
     *
     * @mbg.generated
     */
    public String getFriend() {
        return friend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friend
     *
     * @param friend the value for friends.friend
     *
     * @mbg.generated
     */
    public void setFriend(String friend) {
        this.friend = friend == null ? null : friend.trim();
    }
}